---
title: "Manuscript"
author: "Laura Super"
geometry: margin=1in
output: pdf_document
csl: https://www.zotero.org/styles/ecology-letters
bibliography: new_export-data.bib
---

**Title**: Phytobiomes rule: starting off with height and treatments

Laura Super^1\*^

1.  Department of PREE CIEE fun, at UBC Vancouver and beyond!

\*Corresponding author

\newpage

# Abstract

This is on the phytobiome. It makes a simple graph! It is for a PREE demo that is short and sweet.

*Keywords: phytobiome, nitrogen, warming, height*

# Introduction

Phytobiomes are plants, their associated organisms and environment. Networks of associated organisms with plants are often impacted by treatments, subsequently impacting plant performance in complex ways, including in response to anthropogenic change that are currently of interest such as drought with climate change warming [\@muller_drought_nodate].

# Methods

This project has microbiome and plant data.

# Results

Plant performance was impacted by the treatments. Run code!

# Discussion

Wow happy this is done :)!

# References

::: {#refs}
:::

# Tables

None for this demo!

# Figures

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## Read file into R
data_PREE <- read.csv("../data/CIEE_Course_Teaching_Nema_Phytobiome.csv") # Teaching phytobiome data
head(data_PREE) # head of data

## Make graph
boxplot(data_PREE$Heightwk9_cm ~ data_PREE$Treatment, xlab = "Treatment", ylab = "Height (cm)") # plot plant height versus treatments

```

# Appendices

Wow all done!
